### Salaries Dataset Cleaning and Aggregation

##### This notebooks highlights case study analysis on salaries dataset gathered from Kaggle, and will be used to highlight:
- Data Ingestion from SQLite
- Data Cleaning Techniques
- Data Aggregations and Pivot Tables
- Exploratory Data Analysis (EDA)

### Data Ingestion using SQLAlchemy

In [ ]:
# import necessary libraries
from sqlalchemy import create_engine, text
from typing import List, Dict
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [449]:
# load the database file using function
def load_db(eng: str, query: str) -> pd.DataFrame:

    with eng.connect() as conn:
        return pd.read_sql_query(query, conn)

In [450]:
# load data
engine = create_engine("sqlite:///../data/raw/database.sqlite")
df = load_db(engine, "SELECT * FROM Salaries")
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,,San Francisco,
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,,San Francisco,
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [451]:
df.shape[0]

148654

In [452]:
# inspect data
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148654 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          148654 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             148654 non-null  object
 11  Agency            148654 non-null  object
 12  Status            148654 non-null  object
dtypes: float64(2), int64(2), object(9)
memory usage: 14.7+ MB

Id                  0
EmployeeName        0
JobTitle            0
BasePay             0
OvertimePay         0
OtherPay            0
Benefits            0
TotalPay            0
TotalPayBenefits    0
Year                0
Notes               0
Agency              0
Status              0
dtype: int64

In [453]:
df.describe()

                  Id       TotalPay  TotalPayBenefits           Year
count  148654.000000  148654.000000     148654.000000  148654.000000
mean    74327.500000   74768.321972      93692.554811    2012.522643
std     42912.857795   50517.005274      62793.533483       1.117538
min         1.000000    -618.130000       -618.130000    2011.000000
25%     37164.250000   36168.995000      44065.650000    2012.000000
50%     74327.500000   71426.610000      92404.090000    2013.000000
75%    111490.750000  105839.135000     132876.450000    2014.000000
max    148654.000000  567595.430000     567595.430000    2014.000000

### Cleaning Pipeline

In [454]:
# standardize columns

# remove the id column
df = df.drop(columns=['Id', 'Notes'])
headers = [
    "employee_name", "job_title", "base_pay", "overtime_pay", 
    "other_pay", "benefits", "total_pay", "total_pay_benefits", 
    "year", "agency", "status" 
]
df.columns = headers
df

,employee_name,job_title,base_pay,overtime_pay,other_pay,benefits,total_pay,total_pay_benefits,year,agency,status
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,567595.43,567595.43,2011,San Francisco,
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,,538909.28,538909.28,2011,San Francisco,
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,San Francisco,
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,San Francisco,
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,San Francisco,PT
148650,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,San Francisco,
148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,San Francisco,
148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,San Francisco,
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,San Francisco,PT

In [455]:
import re
# standardize employee names to title
df["employee_name"] = df["employee_name"].apply(lambda s: s.title())

# standardize job_title col
df["job_title"] = df["job_title"].apply(lambda j: j.title())

roman_map = ['I', 'Ii', 'Iii', 'Iv', 'Vi', 'Vii', 'Viii', 'Ix', 'X', "Xiv", "Xvii", "Xvi", "Xviii", "Xv"]
pattern = r'\b(' + '|'.join(roman_map) + r')\b'

df['job_title'] = df['job_title'].str.replace(
    pattern, 
    lambda m: m.group(0).upper(), 
    regex=True
)

In [456]:
df["job_title"].value_counts()

job_title
Transit Operator                  9424
Special Nurse                     5791
Registered Nurse                  4955
Custodian                         3214
Firefighter                       3153
                                  ...
Captain, (Fire Department)           1
Sr Cnselor, Juv Hall (Sfers)         1
Forensic Toxicologist Supervis       1
Conversion                           1
Cashier 3                            1
Name: count, Length: 1637, dtype: int64

In [457]:
# a function to clean numerics for a more cleaner approach and avoid repetition
def clean_numerics(df: pd.DataFrame, col: str):

    if df.empty:
        raise ValueError("The DataFrame is Empty")
    
    df[col] = (
        df[col]
        .astype(str)
        .replace("", 0)
        .str.strip()
    )

    return pd.to_numeric(df[col], errors='coerce')

In [458]:
# for the base pay
df["base_pay"].value_counts()

df["base_pay"] = clean_numerics(df, "base_pay")
df["overtime_pay"] = clean_numerics(df, "overtime_pay")
df["other_pay"] = clean_numerics(df, "other_pay")
df["benefits"] = clean_numerics(df, "benefits")

# I was thinking if to drop both columns with unprovided job title and 0 base pay (so I did.)
df = df[(df["job_title"] != "Not Provided") & (df["base_pay"] != 0)]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147352 entries, 0 to 148620
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   employee_name       147352 non-null  object
 1   job_title           147352 non-null  object
 2   base_pay            146747 non-null  float64
 3   overtime_pay        147352 non-null  float64
 4   other_pay           147352 non-null  float64
 5   benefits            111645 non-null  float64
 6   total_pay           147352 non-null  float64
 7   total_pay_benefits  147352 non-null  float64
 8   year                147352 non-null  int64
 9   agency              147352 non-null  object
 10  status              147352 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 13.5+ MB

In [459]:
check_cols = ['base_pay', 'overtime_pay', 'other_pay', 'benefits', 'total_pay', 'total_pay_benefits']

# checking for negative columns count
for cols in check_cols:
    negative = (df[cols] < 0).sum()
    print(f"{cols} has a negative count: {negative}")

df_clean = df[~(df[check_cols] < 0).any(axis=1)]
df_clean

base_pay has a negative count: 11
overtime_pay has a negative count: 1
other_pay has a negative count: 4
benefits has a negative count: 3
total_pay has a negative count: 0
total_pay_benefits has a negative count: 3

,employee_name,job_title,base_pay,overtime_pay,other_pay,benefits,total_pay,total_pay_benefits,year,agency,status
0,Nathaniel Ford,General Manager-Metropolitan Transit Authority,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,San Francisco,
1,Gary Jimenez,Captain III (Police Department),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,San Francisco,
2,Albert Pardini,Captain III (Police Department),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,San Francisco,
3,Christopher Chong,Wire Rope Cable Maintenance Mechanic,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,San Francisco,
4,Patrick Gardner,"Deputy Chief Of Department,(Fire Department)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...
148613,Nanette M Lloyd,Special Nurse,19.97,0.00,0.00,4.30,19.97,24.27,2014,San Francisco,PT
148616,Afakasi O Afakasi,Public Service Trainee,21.48,0.00,0.86,0.22,22.34,22.56,2014,San Francisco,PT
148617,Charles F Williams Iii,Pool Lifeguard,17.26,0.00,0.00,4.04,17.26,21.30,2014,San Francisco,PT
148619,Ian V Cameron,Is Program Analyst-Assistant,6.04,0.00,10.05,2.30,16.09,18.39,2014,San Francisco,PT
148620,India C Sabater,Recreation Leader,15.50,0.00,0.00,0.16,15.50,15.66,2014,San Francisco,PT

In [460]:
# for status col
status_map = {
    "FT" : "Full Time",
    "PT" : "Part Time"
}

df["status"] = (
    df["status"]
    .replace(status_map)
    .replace("", "Not Specified")
)

df

C:\Users\LEI\AppData\Local\Temp\ipykernel_9256\1828859206.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["status"] = (

,employee_name,job_title,base_pay,overtime_pay,other_pay,benefits,total_pay,total_pay_benefits,year,agency,status
0,Nathaniel Ford,General Manager-Metropolitan Transit Authority,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,San Francisco,Not Specified
1,Gary Jimenez,Captain III (Police Department),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,San Francisco,Not Specified
2,Albert Pardini,Captain III (Police Department),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,San Francisco,Not Specified
3,Christopher Chong,Wire Rope Cable Maintenance Mechanic,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,San Francisco,Not Specified
4,Patrick Gardner,"Deputy Chief Of Department,(Fire Department)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,San Francisco,Not Specified
...,...,...,...,...,...,...,...,...,...,...,...
148613,Nanette M Lloyd,Special Nurse,19.97,0.00,0.00,4.30,19.97,24.27,2014,San Francisco,Part Time
148616,Afakasi O Afakasi,Public Service Trainee,21.48,0.00,0.86,0.22,22.34,22.56,2014,San Francisco,Part Time
148617,Charles F Williams Iii,Pool Lifeguard,17.26,0.00,0.00,4.04,17.26,21.30,2014,San Francisco,Part Time
148619,Ian V Cameron,Is Program Analyst-Assistant,6.04,0.00,10.05,2.30,16.09,18.39,2014,San Francisco,Part Time
148620,India C Sabater,Recreation Leader,15.50,0.00,0.00,0.16,15.50,15.66,2014,San Francisco,Part Time

In [461]:
df.loc[:, "base_pay"] = df["base_pay"].fillna(df.groupby('job_title')["base_pay"].transform(np.median))
df.loc[:, "base_pay"] = df["base_pay"].fillna(np.median)

df.loc[:, "benefits"] = df["benefits"].fillna(0)
df

C:\Users\LEI\AppData\Local\Temp\ipykernel_9256\532354300.py:1: FutureWarning: The provided callable <function median at 0x0000017C2B46A340> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.loc[:, "base_pay"] = df["base_pay"].fillna(df.groupby('job_title')["base_pay"].transform(np.median))
C:\Users\LEI\AppData\Local\Temp\ipykernel_9256\532354300.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[167411.18 155966.02 212739.13 ... 17.26 6.04 15.5]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, "base_pay"] = df["base_pay"].fillna(np.median)

,employee_name,job_title,base_pay,overtime_pay,other_pay,benefits,total_pay,total_pay_benefits,year,agency,status
0,Nathaniel Ford,General Manager-Metropolitan Transit Authority,167411.18,0.00,400184.25,0.00,567595.43,567595.43,2011,San Francisco,Not Specified
1,Gary Jimenez,Captain III (Police Department),155966.02,245131.88,137811.38,0.00,538909.28,538909.28,2011,San Francisco,Not Specified
2,Albert Pardini,Captain III (Police Department),212739.13,106088.18,16452.60,0.00,335279.91,335279.91,2011,San Francisco,Not Specified
3,Christopher Chong,Wire Rope Cable Maintenance Mechanic,77916.0,56120.71,198306.90,0.00,332343.61,332343.61,2011,San Francisco,Not Specified
4,Patrick Gardner,"Deputy Chief Of Department,(Fire Department)",134401.6,9737.00,182234.59,0.00,326373.19,326373.19,2011,San Francisco,Not Specified
...,...,...,...,...,...,...,...,...,...,...,...
148613,Nanette M Lloyd,Special Nurse,19.97,0.00,0.00,4.30,19.97,24.27,2014,San Francisco,Part Time
148616,Afakasi O Afakasi,Public Service Trainee,21.48,0.00,0.86,0.22,22.34,22.56,2014,San Francisco,Part Time
148617,Charles F Williams Iii,Pool Lifeguard,17.26,0.00,0.00,4.04,17.26,21.30,2014,San Francisco,Part Time
148619,Ian V Cameron,Is Program Analyst-Assistant,6.04,0.00,10.05,2.30,16.09,18.39,2014,San Francisco,Part Time
148620,India C Sabater,Recreation Leader,15.5,0.00,0.00,0.16,15.50,15.66,2014,San Francisco,Part Time

### Final Data Inspection

In [462]:
df.isna().sum()

employee_name         0
job_title             0
base_pay              0
overtime_pay          0
other_pay             0
benefits              0
total_pay             0
total_pay_benefits    0
year                  0
agency                0
status                0
dtype: int64

In [463]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147352 entries, 0 to 148620
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   employee_name       147352 non-null  object
 1   job_title           147352 non-null  object
 2   base_pay            147352 non-null  object
 3   overtime_pay        147352 non-null  float64
 4   other_pay           147352 non-null  float64
 5   benefits            147352 non-null  float64
 6   total_pay           147352 non-null  float64
 7   total_pay_benefits  147352 non-null  float64
 8   year                147352 non-null  int64
 9   agency              147352 non-null  object
 10  status              147352 non-null  object
dtypes: float64(5), int64(1), object(5)
memory usage: 13.5+ MB

In [464]:
df.shape[0]

147352

### Load Clean Data

In [465]:
clean = df
clean.to_csv("../data/processed/clean_data.csv")

### Exploratory Data Analysis

In [ ]:
# function to create Aggregation Tables
def agg_tables(df: pd.DataFrame, grp_key: List[str], aggfunc: Dict[str, str]) -> pd.DataFrame:

    if df.empty:
        raise ValueError("The DataFrame is empty")
    
    return df.groupby(grp_key).agg(aggfunc).reset_index()

# function to create Piv Tables
def piv_tables(df: pd.DataFrame, idx: List[str], cols: List[str], aggfunc: List[str] | None, values: List[str]) -> pd.pivot_table:

    if df.empty:
        raise ValueError("The DataFrame is empty")
    
    return df.pivot_table(index=idx, values=values, columns=cols, aggfunc=aggfunc | None)